version: '2.1'
services:
  patient-bff:
    image: kvalitetsit/hjemmebehandling-patient-bff:latest
    ports:
      - 8080:8080
      - 5005:5005
    environment:
      - allowed_origins=http://localhost:3000
      - user.context.handler=MOCK
      - user.mock.context.cpr=0101010101
      - usercontext_header_name=X-Test-Auth
      - userattributes_role_key=UserRoles
      - userattributes_org_key=organisation
      - userrole_admin_values=adminrole
      - userrole_user_values=userrole1,userrole2
      - userrole_monitor_values=monitorrole
      - userrole_provisioner_values=provisionerrole
      - JVM_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    networks:
      - hjemmebehandling_patient

  hapi-server:
    image: kvalitetsit/hjemmebehandling-hapi-fhir-server:dev
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres:5432/hapi
      - spring.datasource.username=hapi
      - spring.datasource.password=hapi
    depends_on:
      - postgres
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/fhir/metadata" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

    networks:
      - hjemmebehandling_patient

  hapi-server-initializer:
    image: kvalitetsit/hjemmebehandling-data-initializer:latest
    depends_on:
      hapi-server:
        condition: service_healthy
    environment:
      - init_test_data=true
    networks:
      - hjemmebehandling_patient

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=hapi
      - POSTGRES_PASSWORD=hapi
      - POSTGRES_ROOT_PASSWORD=hapi
      - POSTGRES_DATABASE=hapi
    networks:
      - hjemmebehandling_patient
    ports:
      - 5432:5432

networks:
  hjemmebehandling_patient:
    driver: bridge